name: test

on:
  push:
    branches:
      - development
      - tests
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...